[build]
builder = "NIXPACKS"
buildCommand = "echo 'Skipping build, pre-built dist folder is already present'"

[deploy]
startCommand = "npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
